alias ls="ls -G"
alias gti="git"
alias nb="/Applications/NetBeans/NetBeans\ 8.0.app/Contents/Resources/NetBeans/bin/netbeans"
alias nbo="nb --open"
alias higrep="history|grep "
alias cab="mvn clean install"
alias fetch="git fetch"
#alias pull="git pull --ff origin $(git branch | grep "*" | sed "s/* //")"
#alias remdiff="git diff --color --stat ...origin/$(git branch | grep "*" | sed "s/* //")|cat"
alias locdiff="git diff --color --stat |cat"
alias gstat="git status"
alias lock="/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine"
alias dev="cd ~/dev"
alias st="/Applications/SourceTree.app/Contents/Resources/stree "
#alias find="gfind"
alias attendance="pmset -g log|grep -e ' Sleep  ' -e ' Wake  '"
alias att=attendance
alias sleepnow="pmset sleepnow"
alias filehist="gitk --all "
alias gpull="git pull --ff origin dev"
alias xo="open *.xcodeproj"
alias belis="shellquery mirror_belis"
alias verdis="shellquery mirror_grundis"
alias grundis="shellquery mirror_grundis"
alias wunda="shellquery mirror_wunda_live"
alias pohu="git push -u origin HEAD"
alias poh="git push origin HEAD"
alias gpd="git pull --ff origin dev"
alias wuppTunnel="sudo ssh -i /Users/thorsten/.ssh/id_dsa  -F ~/.ssh/config tunnels"
alias tw='open -a /Applications/TextWrangler.app'
alias dbuild='docker build '
alias dps='docker ps '
alias drm='docker rm '
alias drun='docker run '
alias dstop='docker stop '
alias dlogs='docker logs '
alias drestart='docker restart '
alias dex='docker exec -it ' 
alias dco='docker-compose ' 
